---
kind: Service
apiVersion: v1
metadata:
  name: logstash-master
  labels:
    app: logstash
    chart: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - name: http
      port: 9600
      nodePort: 31123
    - name: tcp
      port: 9500
      nodePort: 30123
